### PR TITLE
Fixed tests

### PR DESCRIPTION
**Pull request by Phil91**
Tests successfully pass with npm / yarn test.

Edited package-lock.json edited version number of react-test-renderer package.

### CODE REVIEW

**Comment by mcnamee** [comment]
Thanks heaps @Phil91 - unfortunately I'm getting:

```
TypeError: Cannot read property 'ReactCurrentOwner' of undefined
```

When running `npm test`. Any tips?

- Cloned repo
- `npm i`
- Setup `.env` file
- `npm test`: 27 of 27 failed - they all fail with the above error

**Comment by Phil91** [comment]
Could you try deleting the node_modules and try it again.

**Comment by mcnamee** [comment]
Good call - that worked. I started from scratch and it worked this time!

Thanks again @Phil91

**Comment by mcnamee** [comment]
It's really odd @Phil91 - it's showing the same error that I originally received on Travis CI:
https://travis-ci.org/mcnamee/react-native-starter-app/jobs/280384590

Any hints or suggestions?

**Comment by Phil91** [comment]
First guess would be that you've enabled caching for the node_modules.
Try to disable it for the first run and than enable it again.

**Comment by mcnamee** [comment]
Hi @Phil91 Builds are still failing:

https://travis-ci.org/mcnamee/react-native-starter-app/builds/284233669?utm_source=github_status&utm_medium=notification

Do you know how to disable cache on Travis? My understanding is that you have to enable cache, as opposed to disabling it.

**Pull request merged**
